paths:
  data: src/data
  static: public
  uploads: public/uploads

# -----------------------------------------------
# Cloudcannn sidebar configuration
# -----------------------------------------------

collection_groups:
  - heading: Pages
    collections:
      - pages
      - landing
      - legal
  - heading: Products
    collections:
      - collections
      - products
# -----------------------------------------------
# Collection configuration
# -----------------------------------------------

collections_config:
  data:
    path: src/data
    disable_add: true
    disable_add_folder: true
  pages:
    path: src/content/pages
    url: /[full_slug]/
    output: true
    icon: wysiwyg
    disable_add: true
    disable_add_folder: true
    _enabled_editors:
      - visual
  collections:
    path: src/content/collections
    output: true
    icon: grid_view
    _enabled_editors:
      - data
  legal:
    path: src/content/legal
    output: true
    icon: description
    _enabled_editors:
      - content

# -----------------------------------------------
# Input customization
# -----------------------------------------------

_inputs:
  layout:
    hidden: true

  noindex:
    hidden: true

  seo:
    label: SEO
    comment: Search engine optimization

  seo.title:
    label: Meta title
    comment: Aim for 50-60 characters

  seo.description:
    label: Meta description
    comment: Aim for 50-120 characters

  seo.image:
    label: Page image
    comment: Displayed when sharing a link to this page

  seo.noindex:
    label: Noindex
    comment: Prevent search engines from indexing this page

  seo.canonical:
    label: Canonical URL
    comment: The preferred URL for this page, meaning the url search engines will index, instead of the current one

  image.src:
    type: image
    label: Upload
    correct_orientation: false

  image.alt:
    label: Description

  href:
    type: url
    label: Link
